### ISSUE TITLE
nerdtree を表示してる際表示が崩れる

### ISSUE THREAD

**Issue by 39e** [zchee/nvim-go#1]
[nerdtree](https://github.com/scrooloose/nerdtree) を使用してるときに `Gorun` を実行した際表示が崩れました。
[![https://gyazo.com/1281ffcb10edddd93c76cc539e6fe8bc](https://i.gyazo.com/1281ffcb10edddd93c76cc539e6fe8bc.png)](https://gyazo.com/1281ffcb10edddd93c76cc539e6fe8bc)

ちなみに [vim-go](https://github.com/fatih/vim-go) を使用した際は崩れませんでした
[![https://gyazo.com/e20fb995cd56cd06548c45b16c32d4d0](https://i.gyazo.com/e20fb995cd56cd06548c45b16c32d4d0.png)](https://gyazo.com/e20fb995cd56cd06548c45b16c32d4d0)

## Vimのバージョン

```
NVIM v0.2.0-52-g0213e99
Build type: RelWithDebInfo
```

**Comment by zchee** [comment]
@39e Thanks for the first issue!

I'm never used nerdtree, I'll try to debug it.
BTW, Are you same bug using another plugin that will another buffer? such as tagbar.

nerdtreeを使っていないので発見できませんでした、ちょっと調べてみます！
また、例えばtagbar的な他のウィンドウ出るもので同じようなエラーありましたでしょうか？

**Comment by zchee** [comment]
@39e 同じ環境(と同じ39e/go-notify)でテストしてみましたが、再現しませんでした。
最小構成は作るのが面倒かと思いますのでこちらで追求しようかと思っているのですが、init.vimを共有していただくことは可能でしょうか？

**Comment by 39e** [comment]
わかりました。Dotfiles を公開してるので貼っておきます

- [Dotfiles](https://github.com/39e/dotfiles)

**Comment by zchee** [comment]
@39e ありがとうございます。いまこちらにてテスト試みているところです…
https://gist.github.com/zchee/db7ea1500af43ea0093e4f86460134de

**Comment by zchee** [comment]
@39e 完璧に同じ環境は再現できませんでしたが、当たりをつけて修正してみました。自分のデフォルト値の扱いかたに起因した問題だったかと思います。
PRしましたので、お時間あるときにテストしていただけますでしょうか？
https://github.com/zchee/nvim-go/pull/2

**Comment by 39e** [comment]
返信送れてしまい申し訳ありません。確認しましたところ

[![https://gyazo.com/cb44f12afa6d97089a4519d4113a334c](https://i.gyazo.com/cb44f12afa6d97089a4519d4113a334c.png)](https://gyazo.com/cb44f12afa6d97089a4519d4113a334c)

のように表示されるようになりました!

**Comment by 39e** [comment]
[先ほどの部分](https://git.io/vXikx)をコメントアウトしもう一度試してみると以下のようになりました。

[![https://gyazo.com/a75695c6b4a8dc0040df32b99f916ae6](https://i.gyazo.com/a75695c6b4a8dc0040df32b99f916ae6.png)](https://gyazo.com/a75695c6b4a8dc0040df32b99f916ae6)

**Comment by zchee** [comment]
@39e テストありがとうございます！まだ小さそうですね
しかしそれは大きなヒントです！vim-goは`resize`処理があるのですがその辺りも入れないと駄目なんですかね…

> 追記: こちらでいろいろと試した際 ココの部分 が影響してるような気がします。
(何もお手伝いできなくて申し訳にです)

とんでもないです！自分がvimの設定や挙動ほとんど知らないで作ってるので…w　ヒントだけでもありがたいです。
`set splitbelow splitright`まったく知らないので、少し調べてみます。

**Comment by zchee** [comment]
@39e nvimのAPIを使い、`vsplit`などの後にもWidthかHeightを設定するようにしました。再度テストしていただけますでしょうか？
https://github.com/zchee/nvim-go/pull/2/commits/5c47f92cf5d968728decb808e3574d1fa5c6efc4

もし治らないようであれば、一旦vim-goのロジックを忠実に再現するように作り直しますので、その時は少し時間をいただけたらと思います…

**Comment by 39e** [comment]
試してみたところ新規バッファ(かな?)にterminalモードで開くようになりました。

ただ発生条件はわかりませんが以前のように縦長に表示される場合があります...

**Comment by 39e** [comment]
発生条件わかりました。

`nvim hoge` みたいにファイルを指定し起動後 nerdtree を使って同じファイルを開く際一部プラグインが無効化されてるかもしれません...
(これは[vim-jp/issues](https://github.com/vim-jp/issues)に持ち込んだ方がいい問題かも?)

**Comment by zchee** [comment]
@39e テストありがとうございます！発生条件、後で自分でも試してみます。

> 試してみたところ新規バッファ(かな?)にterminalモードで開くようになりました。

これは（発生条件を除いて）vim-goと同じようにちゃんと表示されるようになった、という意味であってますでしょうか？

しかしvim-goでNERDTreeと共存できてるので悔しいですね…
nvim-goは、実際にvimのcommandを呼んでる訳ではなくてMsgpack-RPC越しなのでどのぐらい違いがあるか分かりませんが、もう少し頑張ってみます。

> (これは何処が問題なのか分かりませんが...)

あのNERDTreeの複雑なソースを読む必要がありそうです…が頑張ります…

#2 はとりあえず後でマージします。再度別ブランチ切ってトライします！
ご協力感謝です🙇

**Comment by 39e** [comment]
> vim-goと同じようにちゃんと表示されるようになった

表示されるようになりました!
> vim-goでNERDTreeと共存できてるので悔しいですね…

確かにそうですね
> ご協力感謝です

私は何もできてないので申し訳ないです 🙇
