### ISSUE TITLE
is it fully vim-go compatible?

### ISSUE THREAD

**Issue by nhooyr** [zchee/nvim-go#5]
the TODO.md in the readme is a deadlink, so what is the progress?

**Comment by zchee** [comment]
@nhooyr deadlink is fixed.
https://github.com/zchee/nvim-go/commit/e61537756a7747fa70b8f660fdd03e64e04477fd

but not update to the latest. also will do

**Comment by nhooyr** [comment]
I'm gonna be using this heavily now instead of vim-go so I'll be submitting lots of bug reports/PRS :D

**Comment by nhooyr** [comment]
Also, we should copy the vim-go snippets directory, I'll submit a PR for that soon.

**Comment by zchee** [comment]
@nhooyr 
> I'm gonna be using this heavily now instead of vim-go so I'll be submitting lots of bug reports/PRS :D

Thanks.

> Also, we should copy the vim-go snippets directory, I'll submit a PR for that soon.

Alright. I'm looks forward it.

**Comment by zchee** [comment]
Close via https://github.com/zchee/nvim-go/commit/e61537756a7747fa70b8f660fdd03e64e04477fd
