### ISSUE TITLE
snippets directory

### ISSUE THREAD

**Issue by nhooyr** [zchee/nvim-go#6]
Should we support ultisnips as well, or only neosnippets?

**Comment by zchee** [comment]
@nhooyr I don't like ultisnips because it seems to be incompatible with deoplete.nvim.
So I want to neosnippets only, but leave to you.

**Comment by nhooyr** [comment]
ultisnips is compatible with deoplete.nvim. I use neosnippets as well. Why did you think it wasn't?

**Comment by zchee** [comment]
@nhooyr ah, *it seems*.
Shougo said, Ultisnips uses python interp, that's sometimes conflict(interference) python-client(or deoplete.nvim core.)

**Comment by zchee** [comment]
Close via https://github.com/zchee/nvim-go/pull/7
